# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "TrolleyTracker.xcodeproj")
    commit_version_bump(xcodeproj: "TrolleyTracker.xcodeproj")
    add_git_tag()
    build_app(scheme: "TrolleyTracker")
    upload_to_testflight(username: ENV["FASTLANE_ITC_USERNAME"], skip_submission: true)
  end
  
  desc "Run unit tests"
  lane :test do
    scan(scheme: "TrolleyTracker")
  end
  
end
